version: '3.8'
services:
  nginx:
    container_name: nginx
    ports:
     - 10.2.1.103:80:80
    image: opentracing/nginx-opentracing
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./jaeger-config.json:/etc/jaeger-config.json
      - ./html:/var/www/html
      - ./log/nginx:/var/log/nginx
    restart: always
    networks:
     default:
      ipv4_address: 10.3.34.20 

  dle_php-fpm:
    build:
      context: build_dle_dockerfile/
      dockerfile: ./Dockerfile
    container_name: dle_php-fpm
    # image: dle_php-fpm:0.2
    volumes:
      - ./html:/var/www/html
      - ./log/dle.boyzcraft:/var/log
    restart: always
    networks:
     default:
      ipv4_address: 10.3.34.21


  # mysql:
  #     image: mariadb
  #     container_name: mysql
  #     ports:
  #         - 10.2.1.103:3306:3306
  #     volumes:
  #       - ./mysql:/var/lib/mysql
  #     environment:
  #       MYSQL_ROOT_PASSWORD: pass
  #       MYSQL_DATABASE: db
  #       MYSQL_USER: user
  #       MYSQL_PASSWORD: pass
  #     restart: always
  #     networks:
  #      default:
  #       ipv4_address: 10.3.34.12

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 10.2.1.103:16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
     default:
      ipv4_address: 10.3.34.5  
networks:
  default:
    external: true
    name: docker_dev
# networks:
#  default:
#         name: docker_dev
#         ipam:
#             driver: default
#             config:
#              - subnet: 10.3.34.0/24
#                gateway: 10.3.34.1